#!/usr/bin/perl

use strict;
use warnings;


my $file = shift or die "Usage: ./perl_script <file_name> \n";
my @values;


open my $info, $file or die "Could not open file: '$file' no such file or directory \n";


while (my $line = <$info>) {
	if ($line =~ /NAME/) {
		$line = <$info>;
		#print "$line";
		$line = <$info>;
		#print "$line";
		@values = split (' ', $line);
		if ($values[0] =~ /typedef/ || $values[0] =~ /struct/ || $values[0] =~ /enum/) {
			print $values[1] . "\n";		
		} else {
			print $values[0] . "\n";
		}	
	}
}
