#!/bin/bash

#usage ./run_asciidoc <option "-man" of "-pdf"> <input file> <output file>

if [[ $1 == "-man" ]];
	then 
	./asciidoc-convertor -man $2 > log;

	./function-extractor log > func_name;

	rm log;

	# Read the file in parameter and fill the array named "array"
	getArray() {
	    i=0
	    while read line # Read a line
	    do
		array[i]=$line # Put it into the array
		i=$(($i + 1))
	    done < func_name
	}

	getArray "func_name"

	for i in $@
	do
		for e in "${array[@]}"
		do
		    ./asciidoc-convertor -man -function $e $i > $e.doc;
		    a2x --doctype=manpage --format=manpage  $e.doc;
		done
	done

	rm *.doc func_name

	for e in "${array[@]}"
	do
		    cat $e.9 >> $3;
	done

	rm *.xml
fi

if [[ $1 == "-pdf" ]];
	then
	./asciidoc-convertor -pdf $2 > $3;
	a2x --doctype=article --format=pdf $3;
fi
